//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region BuildVersion
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class BuildVersion :
        global::LightSwitchApplication.BuildVersion.DetailsClass.IImplementation
    {
        partial void OnSystemInformationIDChanged()
        {
            this.___OnPropertyChanged("SystemInformationID");
        }
        
        partial void OnDatabase_VersionChanged()
        {
            this.___OnPropertyChanged("Database_Version");
        }
        
        partial void OnVersionDateChanged()
        {
            this.___OnPropertyChanged("VersionDate");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
    }
    #endregion
    
    #region ErrorLog
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ErrorLog :
        global::LightSwitchApplication.ErrorLog.DetailsClass.IImplementation
    {
        partial void OnErrorLogIDChanged()
        {
            this.___OnPropertyChanged("ErrorLogID");
        }
        
        partial void OnErrorTimeChanged()
        {
            this.___OnPropertyChanged("ErrorTime");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnErrorNumberChanged()
        {
            this.___OnPropertyChanged("ErrorNumber");
        }
        
        partial void OnErrorSeverityChanged()
        {
            this.___OnPropertyChanged("ErrorSeverity");
        }
        
        partial void OnErrorStateChanged()
        {
            this.___OnPropertyChanged("ErrorState");
        }
        
        partial void OnErrorProcedureChanged()
        {
            this.___OnPropertyChanged("ErrorProcedure");
        }
        
        partial void OnErrorLineChanged()
        {
            this.___OnPropertyChanged("ErrorLine");
        }
        
        partial void OnErrorMessageChanged()
        {
            this.___OnPropertyChanged("ErrorMessage");
        }
        
    }
    #endregion
    
    #region Address
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Address :
        global::LightSwitchApplication.Address.DetailsClass.IImplementation
    {
        partial void OnAddressIDChanged()
        {
            this.___OnPropertyChanged("AddressID");
        }
        
        partial void OnAddressLine1Changed()
        {
            this.___OnPropertyChanged("AddressLine1");
        }
        
        partial void OnAddressLine2Changed()
        {
            this.___OnPropertyChanged("AddressLine2");
        }
        
        partial void OnCityChanged()
        {
            this.___OnPropertyChanged("City");
        }
        
        partial void OnStateProvinceChanged()
        {
            this.___OnPropertyChanged("StateProvince");
        }
        
        partial void OnCountryRegionChanged()
        {
            this.___OnPropertyChanged("CountryRegion");
        }
        
        partial void OnPostalCodeChanged()
        {
            this.___OnPropertyChanged("PostalCode");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Address.DetailsClass.IImplementation.CustomerAddresses
        {
            get
            {
                return this.CustomerAddresses;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CustomerAddress> __CustomerAddresses
        {
            get
            {
                if (this.___CustomerAddresses == null)
                {
                    this.___CustomerAddresses = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CustomerAddress>(
                        this,
                        "CustomerAddresses",
                        () => this._CustomerAddresses,
                        e => global::System.Object.Equals(e.AddressID, this.AddressID));
                }
                return this.___CustomerAddresses;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CustomerAddress> ___CustomerAddresses;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Address.DetailsClass.IImplementation.SalesOrderHeaders
        {
            get
            {
                return this.SalesOrderHeaders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader> __SalesOrderHeaders
        {
            get
            {
                if (this.___SalesOrderHeaders == null)
                {
                    this.___SalesOrderHeaders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader>(
                        this,
                        "SalesOrderHeaders",
                        () => this._SalesOrderHeaders,
                        e => global::System.Object.Equals(e.BillToAddressID, this.AddressID));
                }
                return this.___SalesOrderHeaders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader> ___SalesOrderHeaders;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Address.DetailsClass.IImplementation.SalesOrderHeaders1
        {
            get
            {
                return this.SalesOrderHeaders1;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader> __SalesOrderHeaders1
        {
            get
            {
                if (this.___SalesOrderHeaders1 == null)
                {
                    this.___SalesOrderHeaders1 = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader>(
                        this,
                        "SalesOrderHeaders1",
                        () => this._SalesOrderHeaders1,
                        e => global::System.Object.Equals(e.ShipToAddressID, this.AddressID));
                }
                return this.___SalesOrderHeaders1;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader> ___SalesOrderHeaders1;
        
    }
    #endregion
    
    #region Customer
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Customer :
        global::LightSwitchApplication.Customer.DetailsClass.IImplementation
    {
        partial void OnCustomerIDChanged()
        {
            this.___OnPropertyChanged("CustomerID");
        }
        
        partial void OnNameStyleChanged()
        {
            this.___OnPropertyChanged("NameStyle");
        }
        
        partial void OnTitleChanged()
        {
            this.___OnPropertyChanged("Title");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnMiddleNameChanged()
        {
            this.___OnPropertyChanged("MiddleName");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnSuffixChanged()
        {
            this.___OnPropertyChanged("Suffix");
        }
        
        partial void OnCompanyNameChanged()
        {
            this.___OnPropertyChanged("CompanyName");
        }
        
        partial void OnSalesPersonChanged()
        {
            this.___OnPropertyChanged("SalesPerson");
        }
        
        partial void OnEmailAddressChanged()
        {
            this.___OnPropertyChanged("EmailAddress");
        }
        
        partial void OnPhoneChanged()
        {
            this.___OnPropertyChanged("Phone");
        }
        
        partial void OnPasswordHashChanged()
        {
            this.___OnPropertyChanged("PasswordHash");
        }
        
        partial void OnPasswordSaltChanged()
        {
            this.___OnPropertyChanged("PasswordSalt");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Customer.DetailsClass.IImplementation.CustomerAddresses
        {
            get
            {
                return this.CustomerAddresses;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CustomerAddress> __CustomerAddresses
        {
            get
            {
                if (this.___CustomerAddresses == null)
                {
                    this.___CustomerAddresses = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CustomerAddress>(
                        this,
                        "CustomerAddresses",
                        () => this._CustomerAddresses,
                        e => global::System.Object.Equals(e.CustomerID, this.CustomerID));
                }
                return this.___CustomerAddresses;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CustomerAddress> ___CustomerAddresses;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Customer.DetailsClass.IImplementation.SalesOrderHeaders
        {
            get
            {
                return this.SalesOrderHeaders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader> __SalesOrderHeaders
        {
            get
            {
                if (this.___SalesOrderHeaders == null)
                {
                    this.___SalesOrderHeaders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader>(
                        this,
                        "SalesOrderHeaders",
                        () => this._SalesOrderHeaders,
                        e => global::System.Object.Equals(e.CustomerID, this.CustomerID));
                }
                return this.___SalesOrderHeaders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderHeader> ___SalesOrderHeaders;
        
    }
    #endregion
    
    #region CustomerAddress
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CustomerAddress :
        global::LightSwitchApplication.CustomerAddress.DetailsClass.IImplementation
    {
        partial void OnAddressIDChanged()
        {
            this.___OnPropertyChanged("AddressID");
            this.___OnPropertyChanged("Address");
        }
        
        partial void OnCustomerIDChanged()
        {
            this.___OnPropertyChanged("CustomerID");
            this.___OnPropertyChanged("Customer");
        }
        
        partial void OnAddressTypeChanged()
        {
            this.___OnPropertyChanged("AddressType");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CustomerAddress.DetailsClass.IImplementation.Address
        {
            get
            {
                return this.Address;
            }
            set
            {
                this.Address = (global::LightSwitchApplication.Implementation.Address)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address> __Address
        {
            get
            {
                if (this.___Address == null)
                {
                    this.___Address = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address>(
                        this,
                        "Address",
                        new string[] { "AddressID" },
                        e => global::System.Object.Equals(e.AddressID, this.AddressID),
                        () => this._Address,
                        e => this._Address = e);
                }
                return this.___Address;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address> ___Address;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CustomerAddress.DetailsClass.IImplementation.Customer
        {
            get
            {
                return this.Customer;
            }
            set
            {
                this.Customer = (global::LightSwitchApplication.Implementation.Customer)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> __Customer
        {
            get
            {
                if (this.___Customer == null)
                {
                    this.___Customer = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer>(
                        this,
                        "Customer",
                        new string[] { "CustomerID" },
                        e => global::System.Object.Equals(e.CustomerID, this.CustomerID),
                        () => this._Customer,
                        e => this._Customer = e);
                }
                return this.___Customer;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> ___Customer;
        
    }
    #endregion
    
    #region Product
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Product :
        global::LightSwitchApplication.Product.DetailsClass.IImplementation
    {
        partial void OnProductCategoryIDChanged()
        {
            this.___OnPropertyChanged("ProductCategoryID");
            this.___OnPropertyChanged("ProductCategory");
        }
        
        partial void OnProductModelIDChanged()
        {
            this.___OnPropertyChanged("ProductModelID");
            this.___OnPropertyChanged("ProductModel");
        }
        
        partial void OnProductIDChanged()
        {
            this.___OnPropertyChanged("ProductID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnProductNumberChanged()
        {
            this.___OnPropertyChanged("ProductNumber");
        }
        
        partial void OnColorChanged()
        {
            this.___OnPropertyChanged("Color");
        }
        
        partial void OnStandardCostChanged()
        {
            this.___OnPropertyChanged("StandardCost");
        }
        
        partial void OnListPriceChanged()
        {
            this.___OnPropertyChanged("ListPrice");
        }
        
        partial void OnSizeChanged()
        {
            this.___OnPropertyChanged("Size");
        }
        
        partial void OnWeightChanged()
        {
            this.___OnPropertyChanged("Weight");
        }
        
        partial void OnSellStartDateChanged()
        {
            this.___OnPropertyChanged("SellStartDate");
        }
        
        partial void OnSellEndDateChanged()
        {
            this.___OnPropertyChanged("SellEndDate");
        }
        
        partial void OnDiscontinuedDateChanged()
        {
            this.___OnPropertyChanged("DiscontinuedDate");
        }
        
        partial void OnThumbNailPhotoChanged()
        {
            this.___OnPropertyChanged("ThumbNailPhoto");
        }
        
        partial void OnThumbnailPhotoFileNameChanged()
        {
            this.___OnPropertyChanged("ThumbnailPhotoFileName");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Product.DetailsClass.IImplementation.ProductCategory
        {
            get
            {
                return this.ProductCategory;
            }
            set
            {
                this.ProductCategory = (global::LightSwitchApplication.Implementation.ProductCategory)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory> __ProductCategory
        {
            get
            {
                if (this.___ProductCategory == null)
                {
                    this.___ProductCategory = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory>(
                        this,
                        "ProductCategory",
                        new string[] { "ProductCategoryID" },
                        e => global::System.Object.Equals(e.ProductCategoryID, this.ProductCategoryID),
                        () => this._ProductCategory,
                        e => this._ProductCategory = e);
                }
                return this.___ProductCategory;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory> ___ProductCategory;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Product.DetailsClass.IImplementation.ProductModel
        {
            get
            {
                return this.ProductModel;
            }
            set
            {
                this.ProductModel = (global::LightSwitchApplication.Implementation.ProductModel)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductModel> __ProductModel
        {
            get
            {
                if (this.___ProductModel == null)
                {
                    this.___ProductModel = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductModel>(
                        this,
                        "ProductModel",
                        new string[] { "ProductModelID" },
                        e => global::System.Object.Equals(e.ProductModelID, this.ProductModelID),
                        () => this._ProductModel,
                        e => this._ProductModel = e);
                }
                return this.___ProductModel;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductModel> ___ProductModel;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Product.DetailsClass.IImplementation.SalesOrderDetails
        {
            get
            {
                return this.SalesOrderDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderDetail> __SalesOrderDetails
        {
            get
            {
                if (this.___SalesOrderDetails == null)
                {
                    this.___SalesOrderDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderDetail>(
                        this,
                        "SalesOrderDetails",
                        () => this._SalesOrderDetails,
                        e => global::System.Object.Equals(e.ProductID, this.ProductID));
                }
                return this.___SalesOrderDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderDetail> ___SalesOrderDetails;
        
    }
    #endregion
    
    #region ProductCategory
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProductCategory :
        global::LightSwitchApplication.ProductCategory.DetailsClass.IImplementation
    {
        partial void OnParentProductCategoryIDChanged()
        {
            this.___OnPropertyChanged("ParentProductCategoryID");
            this.___OnPropertyChanged("ProductCategory1");
        }
        
        partial void OnProductCategoryIDChanged()
        {
            this.___OnPropertyChanged("ProductCategoryID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProductCategory.DetailsClass.IImplementation.Products
        {
            get
            {
                return this.Products;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product> __Products
        {
            get
            {
                if (this.___Products == null)
                {
                    this.___Products = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product>(
                        this,
                        "Products",
                        () => this._Products,
                        e => global::System.Object.Equals(e.ProductCategoryID, this.ProductCategoryID));
                }
                return this.___Products;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product> ___Products;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProductCategory.DetailsClass.IImplementation.ProductCategories
        {
            get
            {
                return this.ProductCategories;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductCategory> __ProductCategories
        {
            get
            {
                if (this.___ProductCategories == null)
                {
                    this.___ProductCategories = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductCategory>(
                        this,
                        "ProductCategories",
                        () => this._ProductCategories,
                        e => global::System.Object.Equals(e.ParentProductCategoryID, this.ProductCategoryID));
                }
                return this.___ProductCategories;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductCategory> ___ProductCategories;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProductCategory.DetailsClass.IImplementation.ProductCategory1
        {
            get
            {
                return this.ProductCategory1;
            }
            set
            {
                this.ProductCategory1 = (global::LightSwitchApplication.Implementation.ProductCategory)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory> __ProductCategory1
        {
            get
            {
                if (this.___ProductCategory1 == null)
                {
                    this.___ProductCategory1 = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory>(
                        this,
                        "ProductCategory1",
                        new string[] { "ParentProductCategoryID" },
                        e => global::System.Object.Equals(e.ProductCategoryID, this.ParentProductCategoryID),
                        () => this._ProductCategory1,
                        e => this._ProductCategory1 = e);
                }
                return this.___ProductCategory1;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductCategory> ___ProductCategory1;
        
    }
    #endregion
    
    #region ProductDescription
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProductDescription :
        global::LightSwitchApplication.ProductDescription.DetailsClass.IImplementation
    {
        partial void OnProductDescriptionIDChanged()
        {
            this.___OnPropertyChanged("ProductDescriptionID");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProductDescription.DetailsClass.IImplementation.ProductModelProductDescriptions
        {
            get
            {
                return this.ProductModelProductDescriptions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductModelProductDescription> __ProductModelProductDescriptions
        {
            get
            {
                if (this.___ProductModelProductDescriptions == null)
                {
                    this.___ProductModelProductDescriptions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductModelProductDescription>(
                        this,
                        "ProductModelProductDescriptions",
                        () => this._ProductModelProductDescriptions,
                        e => global::System.Object.Equals(e.ProductDescriptionID, this.ProductDescriptionID));
                }
                return this.___ProductModelProductDescriptions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductModelProductDescription> ___ProductModelProductDescriptions;
        
    }
    #endregion
    
    #region ProductModel
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProductModel :
        global::LightSwitchApplication.ProductModel.DetailsClass.IImplementation
    {
        partial void OnProductModelIDChanged()
        {
            this.___OnPropertyChanged("ProductModelID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnCatalogDescriptionChanged()
        {
            this.___OnPropertyChanged("CatalogDescription");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProductModel.DetailsClass.IImplementation.Products
        {
            get
            {
                return this.Products;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product> __Products
        {
            get
            {
                if (this.___Products == null)
                {
                    this.___Products = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product>(
                        this,
                        "Products",
                        () => this._Products,
                        e => global::System.Object.Equals(e.ProductModelID, this.ProductModelID));
                }
                return this.___Products;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Product> ___Products;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProductModel.DetailsClass.IImplementation.ProductModelProductDescriptions
        {
            get
            {
                return this.ProductModelProductDescriptions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductModelProductDescription> __ProductModelProductDescriptions
        {
            get
            {
                if (this.___ProductModelProductDescriptions == null)
                {
                    this.___ProductModelProductDescriptions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductModelProductDescription>(
                        this,
                        "ProductModelProductDescriptions",
                        () => this._ProductModelProductDescriptions,
                        e => global::System.Object.Equals(e.ProductModelID, this.ProductModelID));
                }
                return this.___ProductModelProductDescriptions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProductModelProductDescription> ___ProductModelProductDescriptions;
        
    }
    #endregion
    
    #region ProductModelProductDescription
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProductModelProductDescription :
        global::LightSwitchApplication.ProductModelProductDescription.DetailsClass.IImplementation
    {
        partial void OnProductDescriptionIDChanged()
        {
            this.___OnPropertyChanged("ProductDescriptionID");
            this.___OnPropertyChanged("ProductDescription");
        }
        
        partial void OnProductModelIDChanged()
        {
            this.___OnPropertyChanged("ProductModelID");
            this.___OnPropertyChanged("ProductModel");
        }
        
        partial void OnCultureChanged()
        {
            this.___OnPropertyChanged("Culture");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProductModelProductDescription.DetailsClass.IImplementation.ProductDescription
        {
            get
            {
                return this.ProductDescription;
            }
            set
            {
                this.ProductDescription = (global::LightSwitchApplication.Implementation.ProductDescription)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductDescription> __ProductDescription
        {
            get
            {
                if (this.___ProductDescription == null)
                {
                    this.___ProductDescription = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductDescription>(
                        this,
                        "ProductDescription",
                        new string[] { "ProductDescriptionID" },
                        e => global::System.Object.Equals(e.ProductDescriptionID, this.ProductDescriptionID),
                        () => this._ProductDescription,
                        e => this._ProductDescription = e);
                }
                return this.___ProductDescription;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductDescription> ___ProductDescription;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProductModelProductDescription.DetailsClass.IImplementation.ProductModel
        {
            get
            {
                return this.ProductModel;
            }
            set
            {
                this.ProductModel = (global::LightSwitchApplication.Implementation.ProductModel)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductModel> __ProductModel
        {
            get
            {
                if (this.___ProductModel == null)
                {
                    this.___ProductModel = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductModel>(
                        this,
                        "ProductModel",
                        new string[] { "ProductModelID" },
                        e => global::System.Object.Equals(e.ProductModelID, this.ProductModelID),
                        () => this._ProductModel,
                        e => this._ProductModel = e);
                }
                return this.___ProductModel;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProductModel> ___ProductModel;
        
    }
    #endregion
    
    #region SalesOrderDetail
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SalesOrderDetail :
        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.IImplementation
    {
        partial void OnProductIDChanged()
        {
            this.___OnPropertyChanged("ProductID");
            this.___OnPropertyChanged("Product");
        }
        
        partial void OnSalesOrderIDChanged()
        {
            this.___OnPropertyChanged("SalesOrderID");
            this.___OnPropertyChanged("SalesOrderHeader");
        }
        
        partial void OnSalesOrderDetailIDChanged()
        {
            this.___OnPropertyChanged("SalesOrderDetailID");
        }
        
        partial void OnOrderQtyChanged()
        {
            this.___OnPropertyChanged("OrderQty");
        }
        
        partial void OnUnitPriceChanged()
        {
            this.___OnPropertyChanged("UnitPrice");
        }
        
        partial void OnUnitPriceDiscountChanged()
        {
            this.___OnPropertyChanged("UnitPriceDiscount");
        }
        
        partial void OnLineTotalChanged()
        {
            this.___OnPropertyChanged("LineTotal");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SalesOrderDetail.DetailsClass.IImplementation.Product
        {
            get
            {
                return this.Product;
            }
            set
            {
                this.Product = (global::LightSwitchApplication.Implementation.Product)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> __Product
        {
            get
            {
                if (this.___Product == null)
                {
                    this.___Product = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product>(
                        this,
                        "Product",
                        new string[] { "ProductID" },
                        e => global::System.Object.Equals(e.ProductID, this.ProductID),
                        () => this._Product,
                        e => this._Product = e);
                }
                return this.___Product;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Product> ___Product;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SalesOrderDetail.DetailsClass.IImplementation.SalesOrderHeader
        {
            get
            {
                return this.SalesOrderHeader;
            }
            set
            {
                this.SalesOrderHeader = (global::LightSwitchApplication.Implementation.SalesOrderHeader)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SalesOrderHeader> __SalesOrderHeader
        {
            get
            {
                if (this.___SalesOrderHeader == null)
                {
                    this.___SalesOrderHeader = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SalesOrderHeader>(
                        this,
                        "SalesOrderHeader",
                        new string[] { "SalesOrderID" },
                        e => global::System.Object.Equals(e.SalesOrderID, this.SalesOrderID),
                        () => this._SalesOrderHeader,
                        e => this._SalesOrderHeader = e);
                }
                return this.___SalesOrderHeader;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SalesOrderHeader> ___SalesOrderHeader;
        
    }
    #endregion
    
    #region SalesOrderHeader
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SalesOrderHeader :
        global::LightSwitchApplication.SalesOrderHeader.DetailsClass.IImplementation
    {
        partial void OnBillToAddressIDChanged()
        {
            this.___OnPropertyChanged("BillToAddressID");
            this.___OnPropertyChanged("Address");
        }
        
        partial void OnShipToAddressIDChanged()
        {
            this.___OnPropertyChanged("ShipToAddressID");
            this.___OnPropertyChanged("Address1");
        }
        
        partial void OnCustomerIDChanged()
        {
            this.___OnPropertyChanged("CustomerID");
            this.___OnPropertyChanged("Customer");
        }
        
        partial void OnSalesOrderIDChanged()
        {
            this.___OnPropertyChanged("SalesOrderID");
        }
        
        partial void OnRevisionNumberChanged()
        {
            this.___OnPropertyChanged("RevisionNumber");
        }
        
        partial void OnOrderDateChanged()
        {
            this.___OnPropertyChanged("OrderDate");
        }
        
        partial void OnDueDateChanged()
        {
            this.___OnPropertyChanged("DueDate");
        }
        
        partial void OnShipDateChanged()
        {
            this.___OnPropertyChanged("ShipDate");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnOnlineOrderFlagChanged()
        {
            this.___OnPropertyChanged("OnlineOrderFlag");
        }
        
        partial void OnSalesOrderNumberChanged()
        {
            this.___OnPropertyChanged("SalesOrderNumber");
        }
        
        partial void OnPurchaseOrderNumberChanged()
        {
            this.___OnPropertyChanged("PurchaseOrderNumber");
        }
        
        partial void OnAccountNumberChanged()
        {
            this.___OnPropertyChanged("AccountNumber");
        }
        
        partial void OnShipMethodChanged()
        {
            this.___OnPropertyChanged("ShipMethod");
        }
        
        partial void OnCreditCardApprovalCodeChanged()
        {
            this.___OnPropertyChanged("CreditCardApprovalCode");
        }
        
        partial void OnSubTotalChanged()
        {
            this.___OnPropertyChanged("SubTotal");
        }
        
        partial void OnTaxAmtChanged()
        {
            this.___OnPropertyChanged("TaxAmt");
        }
        
        partial void OnFreightChanged()
        {
            this.___OnPropertyChanged("Freight");
        }
        
        partial void OnTotalDueChanged()
        {
            this.___OnPropertyChanged("TotalDue");
        }
        
        partial void OnCommentChanged()
        {
            this.___OnPropertyChanged("Comment");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SalesOrderHeader.DetailsClass.IImplementation.SalesOrderDetails
        {
            get
            {
                return this.SalesOrderDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderDetail> __SalesOrderDetails
        {
            get
            {
                if (this.___SalesOrderDetails == null)
                {
                    this.___SalesOrderDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderDetail>(
                        this,
                        "SalesOrderDetails",
                        () => this._SalesOrderDetails,
                        e => global::System.Object.Equals(e.SalesOrderID, this.SalesOrderID));
                }
                return this.___SalesOrderDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.SalesOrderDetail> ___SalesOrderDetails;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SalesOrderHeader.DetailsClass.IImplementation.Address
        {
            get
            {
                return this.Address;
            }
            set
            {
                this.Address = (global::LightSwitchApplication.Implementation.Address)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address> __Address
        {
            get
            {
                if (this.___Address == null)
                {
                    this.___Address = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address>(
                        this,
                        "Address",
                        new string[] { "BillToAddressID" },
                        e => global::System.Object.Equals(e.AddressID, this.BillToAddressID),
                        () => this._Address,
                        e => this._Address = e);
                }
                return this.___Address;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address> ___Address;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SalesOrderHeader.DetailsClass.IImplementation.Address1
        {
            get
            {
                return this.Address1;
            }
            set
            {
                this.Address1 = (global::LightSwitchApplication.Implementation.Address)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address> __Address1
        {
            get
            {
                if (this.___Address1 == null)
                {
                    this.___Address1 = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address>(
                        this,
                        "Address1",
                        new string[] { "ShipToAddressID" },
                        e => global::System.Object.Equals(e.AddressID, this.ShipToAddressID),
                        () => this._Address1,
                        e => this._Address1 = e);
                }
                return this.___Address1;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Address> ___Address1;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SalesOrderHeader.DetailsClass.IImplementation.Customer
        {
            get
            {
                return this.Customer;
            }
            set
            {
                this.Customer = (global::LightSwitchApplication.Implementation.Customer)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> __Customer
        {
            get
            {
                if (this.___Customer == null)
                {
                    this.___Customer = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer>(
                        this,
                        "Customer",
                        new string[] { "CustomerID" },
                        e => global::System.Object.Equals(e.CustomerID, this.CustomerID),
                        () => this._Customer,
                        e => this._Customer = e);
                }
                return this.___Customer;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> ___Customer;
        
    }
    #endregion
    
    #region vGetAllCategory
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class vGetAllCategory :
        global::LightSwitchApplication.vGetAllCategory.DetailsClass.IImplementation
    {
        partial void OnParentProductCategoryNameChanged()
        {
            this.___OnPropertyChanged("ParentProductCategoryName");
        }
        
        partial void OnProductCategoryNameChanged()
        {
            this.___OnPropertyChanged("ProductCategoryName");
        }
        
        partial void OnProductCategoryIDChanged()
        {
            this.___OnPropertyChanged("ProductCategoryID");
        }
        
    }
    #endregion
    
    #region vProductAndDescription
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class vProductAndDescription :
        global::LightSwitchApplication.vProductAndDescription.DetailsClass.IImplementation
    {
        partial void OnProductIDChanged()
        {
            this.___OnPropertyChanged("ProductID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnProductModelChanged()
        {
            this.___OnPropertyChanged("ProductModel");
        }
        
        partial void OnCultureChanged()
        {
            this.___OnPropertyChanged("Culture");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
    }
    #endregion
    
    #region vProductModelCatalogDescription
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/AdventureWorksLT2017Data.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class vProductModelCatalogDescription :
        global::LightSwitchApplication.vProductModelCatalogDescription.DetailsClass.IImplementation
    {
        partial void OnProductModelIDChanged()
        {
            this.___OnPropertyChanged("ProductModelID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnSummaryChanged()
        {
            this.___OnPropertyChanged("Summary");
        }
        
        partial void OnManufacturerChanged()
        {
            this.___OnPropertyChanged("Manufacturer");
        }
        
        partial void OnCopyrightChanged()
        {
            this.___OnPropertyChanged("Copyright");
        }
        
        partial void OnProductURLChanged()
        {
            this.___OnPropertyChanged("ProductURL");
        }
        
        partial void OnWarrantyPeriodChanged()
        {
            this.___OnPropertyChanged("WarrantyPeriod");
        }
        
        partial void OnWarrantyDescriptionChanged()
        {
            this.___OnPropertyChanged("WarrantyDescription");
        }
        
        partial void OnNoOfYearsChanged()
        {
            this.___OnPropertyChanged("NoOfYears");
        }
        
        partial void OnMaintenanceDescriptionChanged()
        {
            this.___OnPropertyChanged("MaintenanceDescription");
        }
        
        partial void OnWheelChanged()
        {
            this.___OnPropertyChanged("Wheel");
        }
        
        partial void OnSaddleChanged()
        {
            this.___OnPropertyChanged("Saddle");
        }
        
        partial void OnPedalChanged()
        {
            this.___OnPropertyChanged("Pedal");
        }
        
        partial void OnBikeFrameChanged()
        {
            this.___OnPropertyChanged("BikeFrame");
        }
        
        partial void OnCranksetChanged()
        {
            this.___OnPropertyChanged("Crankset");
        }
        
        partial void OnPictureAngleChanged()
        {
            this.___OnPropertyChanged("PictureAngle");
        }
        
        partial void OnPictureSizeChanged()
        {
            this.___OnPropertyChanged("PictureSize");
        }
        
        partial void OnProductPhotoIDChanged()
        {
            this.___OnPropertyChanged("ProductPhotoID");
        }
        
        partial void OnMaterialChanged()
        {
            this.___OnPropertyChanged("Material");
        }
        
        partial void OnColorChanged()
        {
            this.___OnPropertyChanged("Color");
        }
        
        partial void OnProductLineChanged()
        {
            this.___OnPropertyChanged("ProductLine");
        }
        
        partial void OnStyleChanged()
        {
            this.___OnPropertyChanged("Style");
        }
        
        partial void OnRiderExperienceChanged()
        {
            this.___OnPropertyChanged("RiderExperience");
        }
        
        partial void OnrowguidChanged()
        {
            this.___OnPropertyChanged("rowguid");
        }
        
        partial void OnModifiedDateChanged()
        {
            this.___OnPropertyChanged("ModifiedDate");
        }
        
    }
    #endregion
    
    #region AdventureWorksLT2017Data
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AdventureWorksLT2017Data
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.BuildVersion))
            {
                return new global::LightSwitchApplication.Implementation.BuildVersion();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ErrorLog))
            {
                return new global::LightSwitchApplication.Implementation.ErrorLog();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Address))
            {
                return new global::LightSwitchApplication.Implementation.Address();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Customer))
            {
                return new global::LightSwitchApplication.Implementation.Customer();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CustomerAddress))
            {
                return new global::LightSwitchApplication.Implementation.CustomerAddress();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Product))
            {
                return new global::LightSwitchApplication.Implementation.Product();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProductCategory))
            {
                return new global::LightSwitchApplication.Implementation.ProductCategory();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProductDescription))
            {
                return new global::LightSwitchApplication.Implementation.ProductDescription();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProductModel))
            {
                return new global::LightSwitchApplication.Implementation.ProductModel();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProductModelProductDescription))
            {
                return new global::LightSwitchApplication.Implementation.ProductModelProductDescription();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SalesOrderDetail))
            {
                return new global::LightSwitchApplication.Implementation.SalesOrderDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SalesOrderHeader))
            {
                return new global::LightSwitchApplication.Implementation.SalesOrderHeader();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.vGetAllCategory))
            {
                return new global::LightSwitchApplication.Implementation.vGetAllCategory();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.vProductAndDescription))
            {
                return new global::LightSwitchApplication.Implementation.vProductAndDescription();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.vProductModelCatalogDescription))
            {
                return new global::LightSwitchApplication.Implementation.vProductModelCatalogDescription();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.AdventureWorksLT2017Data.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.AdventureWorksLT2017Data))
            {
                return new global::LightSwitchApplication.AdventureWorksLT2017Data();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.AdventureWorksLT2017Data))
            {
                return new global::LightSwitchApplication.Implementation.AdventureWorksLT2017Data(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../AdventureWorksLT2017Data.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.BuildVersion) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.BuildVersion);
            }
            if (typeof(global::LightSwitchApplication.ErrorLog) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ErrorLog);
            }
            if (typeof(global::LightSwitchApplication.Address) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Address);
            }
            if (typeof(global::LightSwitchApplication.Customer) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Customer);
            }
            if (typeof(global::LightSwitchApplication.CustomerAddress) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CustomerAddress);
            }
            if (typeof(global::LightSwitchApplication.Product) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Product);
            }
            if (typeof(global::LightSwitchApplication.ProductCategory) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProductCategory);
            }
            if (typeof(global::LightSwitchApplication.ProductDescription) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProductDescription);
            }
            if (typeof(global::LightSwitchApplication.ProductModel) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProductModel);
            }
            if (typeof(global::LightSwitchApplication.ProductModelProductDescription) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProductModelProductDescription);
            }
            if (typeof(global::LightSwitchApplication.SalesOrderDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SalesOrderDetail);
            }
            if (typeof(global::LightSwitchApplication.SalesOrderHeader) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SalesOrderHeader);
            }
            if (typeof(global::LightSwitchApplication.vGetAllCategory) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.vGetAllCategory);
            }
            if (typeof(global::LightSwitchApplication.vProductAndDescription) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.vProductAndDescription);
            }
            if (typeof(global::LightSwitchApplication.vProductModelCatalogDescription) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.vProductModelCatalogDescription);
            }
            return null;
        }
    }
}
