

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class ProductCategory : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ProductCategory entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProductCategory()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProductCategory(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProductCategory> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ProductCategory.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductCategory_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductCategory_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ProductCategoryID
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategoryID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductCategoryID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductCategoryID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductCategoryID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.ProductCategory.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid rowguid
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.rowguid);
            }
            set
            {
                global::LightSwitchApplication.ProductCategory.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.rowguid, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.ProductCategory.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Product> Products
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.Products);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Product> ProductsQuery
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetQuery(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.Products);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProductCategory> ProductCategories
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategories);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProductCategory> ProductCategoriesQuery
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetQuery(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategories);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ProductCategory ProductCategory1
        {
            get
            {
                return global::LightSwitchApplication.ProductCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategory1);
            }
            set
            {
                global::LightSwitchApplication.ProductCategory.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategory1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductCategory1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductCategory1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductCategory1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ProductCategory,
                global::LightSwitchApplication.ProductCategory.DetailsClass,
                global::LightSwitchApplication.ProductCategory.DetailsClass.IImplementation,
                global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategoryID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass>.Entry
                __ProductCategoryEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProductCategory.DetailsClass.__ProductCategory_CreateNew,
                    global::LightSwitchApplication.ProductCategory.DetailsClass.__ProductCategory_Created,
                    global::LightSwitchApplication.ProductCategory.DetailsClass.__ProductCategory_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ProductCategory __ProductCategory_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProductCategory> es)
            {
                return new global::LightSwitchApplication.ProductCategory(es);
            }
            private static void __ProductCategory_Created(global::LightSwitchApplication.ProductCategory e)
            {
                e.ProductCategory_Created();
            }
            private static bool __ProductCategory_AllowSaveWithErrors(global::LightSwitchApplication.ProductCategory e)
            {
                bool result = false;
                e.ProductCategory_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, int> ProductCategoryID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategoryID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.Guid> rowguid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.rowguid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.DateTime> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.Product> Products
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.Products) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory> ProductCategories
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategories) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory> ProductCategory1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategory1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ProductCategoryID { get; }
                new string Name { get; set; }
                new global::System.Guid rowguid { get; set; }
                new global::System.DateTime ModifiedDate { get; set; }
                new global::System.Collections.IEnumerable Products { get; }
                new global::System.Collections.IEnumerable ProductCategories { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ProductCategory1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, int>.Entry
                    ProductCategoryID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, int>.Entry(
                        "ProductCategoryID",
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategoryID_Stub,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategoryID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategoryID_Validate,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategoryID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategoryID_OnValueChanged);
                private static void _ProductCategoryID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProductCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductCategoryID, sf);
                }
                private static bool _ProductCategoryID_ComputeIsReadOnly(global::LightSwitchApplication.ProductCategory e)
                {
                    bool result = false;
                    e.ProductCategoryID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductCategoryID_Validate(global::LightSwitchApplication.ProductCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductCategoryID_Validate(r);
                }
                private static int _ProductCategoryID_GetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductCategoryID;
                }
                private static void _ProductCategoryID_OnValueChanged(global::LightSwitchApplication.ProductCategory e)
                {
                    e.ProductCategoryID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProductCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.ProductCategory e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.ProductCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.ProductCategory e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.Guid>.Entry
                    rowguid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.Guid>.Entry(
                        "rowguid",
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._rowguid_Stub,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._rowguid_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._rowguid_Validate,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._rowguid_GetImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._rowguid_SetImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._rowguid_OnValueChanged);
                private static void _rowguid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.ProductCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._rowguid, sf);
                }
                private static bool _rowguid_ComputeIsReadOnly(global::LightSwitchApplication.ProductCategory e)
                {
                    bool result = false;
                    e.rowguid_IsReadOnly(ref result);
                    return result;
                }
                private static void _rowguid_Validate(global::LightSwitchApplication.ProductCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.rowguid_Validate(r);
                }
                private static global::System.Guid _rowguid_GetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.ImplementationEntity.rowguid;
                }
                private static void _rowguid_SetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.rowguid = v;
                }
                private static void _rowguid_OnValueChanged(global::LightSwitchApplication.ProductCategory e)
                {
                    e.rowguid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.DateTime>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.DateTime>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ProductCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.ProductCategory e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.ProductCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.DateTime _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.ProductCategory.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.ProductCategory e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Products = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Products",
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Products_Stub,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Products_GetReferencedEntities,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._Products_GetEntityCollection);
                private static void _Products_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.ProductCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._Products, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Product> _Products_GetReferencedEntities(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.Products, ref d._Products);
                }
                private static global::System.Collections.IEnumerable _Products_GetEntityCollection(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.ImplementationEntity.Products;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>.Entry
                    ProductCategories = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>.Entry(
                        "ProductCategories",
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategories_Stub,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategories_GetReferencedEntities,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategories_GetEntityCollection);
                private static void _ProductCategories_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>.Data> c, global::LightSwitchApplication.ProductCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductCategories, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProductCategory> _ProductCategories_GetReferencedEntities(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass>(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategories, ref d._ProductCategories);
                }
                private static global::System.Collections.IEnumerable _ProductCategories_GetEntityCollection(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductCategories;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>.Entry
                    ProductCategory1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>.Entry(
                        "ProductCategory1",
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategory1_Stub,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategory1_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategory1_Validate,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategory1_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategory1_GetImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategory1_SetImplementationValue,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategory1_Refresh,
                        global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties._ProductCategory1_OnValueChanged);
                private static void _ProductCategory1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>.Data> c, global::LightSwitchApplication.ProductCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductCategory1, sf);
                }
                private static bool _ProductCategory1_ComputeIsReadOnly(global::LightSwitchApplication.ProductCategory e)
                {
                    bool result = false;
                    e.ProductCategory1_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductCategory1_Validate(global::LightSwitchApplication.ProductCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductCategory1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ProductCategory1_GetCoreImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductCategory1;
                }
                private static global::LightSwitchApplication.ProductCategory _ProductCategory1_GetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass>(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategory1, ref d._ProductCategory1);
                }
                private static void _ProductCategory1_SetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass d, global::LightSwitchApplication.ProductCategory v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategory1, ref d._ProductCategory1, (i, ev) => i.ProductCategory1 = ev, v);
                }
                private static void _ProductCategory1_Refresh(global::LightSwitchApplication.ProductCategory.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProductCategory.DetailsClass.PropertySetProperties.ProductCategory1, ref d._ProductCategory1);
                }
                private static void _ProductCategory1_OnValueChanged(global::LightSwitchApplication.ProductCategory e)
                {
                    e.ProductCategory1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, int>.Data _ProductCategoryID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.Guid>.Data _rowguid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::System.DateTime>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.Product>.Data _Products;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>.Data _ProductCategories;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProductCategory, global::LightSwitchApplication.ProductCategory.DetailsClass, global::LightSwitchApplication.ProductCategory>.Data _ProductCategory1;
            
        }
    
        #endregion
    }
    
    #endregion
}
