

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class ProductModel : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ProductModel entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProductModel()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProductModel(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProductModel> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ProductModel.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductModel_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductModel_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ProductModelID
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ProductModelID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductModelID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductModelID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductModelID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.ProductModel.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CatalogDescription
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.CatalogDescription);
            }
            set
            {
                global::LightSwitchApplication.ProductModel.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.CatalogDescription, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogDescription_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogDescription_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CatalogDescription_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid rowguid
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.rowguid);
            }
            set
            {
                global::LightSwitchApplication.ProductModel.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.rowguid, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.ProductModel.DetailsClass.SetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Product> Products
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.Products);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Product> ProductsQuery
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetQuery(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.Products);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProductModelProductDescription> ProductModelProductDescriptions
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetValue(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ProductModelProductDescriptions);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProductModelProductDescription> ProductModelProductDescriptionsQuery
        {
            get
            {
                return global::LightSwitchApplication.ProductModel.DetailsClass.GetQuery(this, global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ProductModelProductDescriptions);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ProductModel,
                global::LightSwitchApplication.ProductModel.DetailsClass,
                global::LightSwitchApplication.ProductModel.DetailsClass.IImplementation,
                global::LightSwitchApplication.ProductModel.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ProductModelID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass>.Entry
                __ProductModelEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProductModel.DetailsClass.__ProductModel_CreateNew,
                    global::LightSwitchApplication.ProductModel.DetailsClass.__ProductModel_Created,
                    global::LightSwitchApplication.ProductModel.DetailsClass.__ProductModel_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ProductModel __ProductModel_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProductModel> es)
            {
                return new global::LightSwitchApplication.ProductModel(es);
            }
            private static void __ProductModel_Created(global::LightSwitchApplication.ProductModel e)
            {
                e.ProductModel_Created();
            }
            private static bool __ProductModel_AllowSaveWithErrors(global::LightSwitchApplication.ProductModel e)
            {
                bool result = false;
                e.ProductModel_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProductModel.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, int> ProductModelID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ProductModelID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string> CatalogDescription
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.CatalogDescription) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.Guid> rowguid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.rowguid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.DateTime> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.Product> Products
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.Products) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.ProductModelProductDescription> ProductModelProductDescriptions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ProductModelProductDescriptions) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.ProductModelProductDescription>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ProductModelID { get; }
                new string Name { get; set; }
                new string CatalogDescription { get; set; }
                new global::System.Guid rowguid { get; set; }
                new global::System.DateTime ModifiedDate { get; set; }
                new global::System.Collections.IEnumerable Products { get; }
                new global::System.Collections.IEnumerable ProductModelProductDescriptions { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, int>.Entry
                    ProductModelID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, int>.Entry(
                        "ProductModelID",
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ProductModelID_Stub,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ProductModelID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ProductModelID_Validate,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ProductModelID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ProductModelID_OnValueChanged);
                private static void _ProductModelID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductModel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProductModel.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductModelID, sf);
                }
                private static bool _ProductModelID_ComputeIsReadOnly(global::LightSwitchApplication.ProductModel e)
                {
                    bool result = false;
                    e.ProductModelID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductModelID_Validate(global::LightSwitchApplication.ProductModel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductModelID_Validate(r);
                }
                private static int _ProductModelID_GetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductModelID;
                }
                private static void _ProductModelID_OnValueChanged(global::LightSwitchApplication.ProductModel e)
                {
                    e.ProductModelID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductModel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProductModel.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.ProductModel e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.ProductModel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.ProductModel e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>.Entry
                    CatalogDescription = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>.Entry(
                        "CatalogDescription",
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._CatalogDescription_Stub,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._CatalogDescription_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._CatalogDescription_Validate,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._CatalogDescription_GetImplementationValue,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._CatalogDescription_SetImplementationValue,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._CatalogDescription_OnValueChanged);
                private static void _CatalogDescription_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductModel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProductModel.DetailsClass d, object sf)
                {
                    c(d, ref d._CatalogDescription, sf);
                }
                private static bool _CatalogDescription_ComputeIsReadOnly(global::LightSwitchApplication.ProductModel e)
                {
                    bool result = false;
                    e.CatalogDescription_IsReadOnly(ref result);
                    return result;
                }
                private static void _CatalogDescription_Validate(global::LightSwitchApplication.ProductModel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CatalogDescription_Validate(r);
                }
                private static string _CatalogDescription_GetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.ImplementationEntity.CatalogDescription;
                }
                private static void _CatalogDescription_SetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CatalogDescription = v;
                }
                private static void _CatalogDescription_OnValueChanged(global::LightSwitchApplication.ProductModel e)
                {
                    e.CatalogDescription_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.Guid>.Entry
                    rowguid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.Guid>.Entry(
                        "rowguid",
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._rowguid_Stub,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._rowguid_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._rowguid_Validate,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._rowguid_GetImplementationValue,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._rowguid_SetImplementationValue,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._rowguid_OnValueChanged);
                private static void _rowguid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductModel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.ProductModel.DetailsClass d, object sf)
                {
                    c(d, ref d._rowguid, sf);
                }
                private static bool _rowguid_ComputeIsReadOnly(global::LightSwitchApplication.ProductModel e)
                {
                    bool result = false;
                    e.rowguid_IsReadOnly(ref result);
                    return result;
                }
                private static void _rowguid_Validate(global::LightSwitchApplication.ProductModel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.rowguid_Validate(r);
                }
                private static global::System.Guid _rowguid_GetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.ImplementationEntity.rowguid;
                }
                private static void _rowguid_SetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.rowguid = v;
                }
                private static void _rowguid_OnValueChanged(global::LightSwitchApplication.ProductModel e)
                {
                    e.rowguid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.DateTime>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.DateTime>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductModel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ProductModel.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.ProductModel e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.ProductModel e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.DateTime _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.ProductModel.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.ProductModel.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.ProductModel e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Products = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Products",
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Products_Stub,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Products_GetReferencedEntities,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._Products_GetEntityCollection);
                private static void _Products_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductModel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.ProductModel.DetailsClass d, object sf)
                {
                    c(d, ref d._Products, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Product> _Products_GetReferencedEntities(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.Products, ref d._Products);
                }
                private static global::System.Collections.IEnumerable _Products_GetEntityCollection(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.ImplementationEntity.Products;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.ProductModelProductDescription>.Entry
                    ProductModelProductDescriptions = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.ProductModelProductDescription>.Entry(
                        "ProductModelProductDescriptions",
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ProductModelProductDescriptions_Stub,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ProductModelProductDescriptions_GetReferencedEntities,
                        global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties._ProductModelProductDescriptions_GetEntityCollection);
                private static void _ProductModelProductDescriptions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProductModel.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.ProductModelProductDescription>.Data> c, global::LightSwitchApplication.ProductModel.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductModelProductDescriptions, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProductModelProductDescription> _ProductModelProductDescriptions_GetReferencedEntities(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProductModelProductDescription, global::LightSwitchApplication.ProductModelProductDescription.DetailsClass>(global::LightSwitchApplication.ProductModel.DetailsClass.PropertySetProperties.ProductModelProductDescriptions, ref d._ProductModelProductDescriptions);
                }
                private static global::System.Collections.IEnumerable _ProductModelProductDescriptions_GetEntityCollection(global::LightSwitchApplication.ProductModel.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductModelProductDescriptions;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, int>.Data _ProductModelID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, string>.Data _CatalogDescription;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.Guid>.Data _rowguid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::System.DateTime>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.Product>.Data _Products;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProductModel, global::LightSwitchApplication.ProductModel.DetailsClass, global::LightSwitchApplication.ProductModelProductDescription>.Data _ProductModelProductDescriptions;
            
        }
    
        #endregion
    }
    
    #endregion
}
