

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class SalesOrderDetail : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the SalesOrderDetail entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SalesOrderDetail()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SalesOrderDetail(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SalesOrderDetail> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.SalesOrderDetail.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetail_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SalesOrderID
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderID);
            }
            set
            {
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SalesOrderDetailID
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderDetailID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetailID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetailID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetailID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short OrderQty
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.OrderQty);
            }
            set
            {
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.OrderQty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderQty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderQty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderQty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal UnitPrice
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.UnitPrice);
            }
            set
            {
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.UnitPrice, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPrice_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPrice_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPrice_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal UnitPriceDiscount
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.UnitPriceDiscount);
            }
            set
            {
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.UnitPriceDiscount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPriceDiscount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPriceDiscount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPriceDiscount_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal LineTotal
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.LineTotal);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LineTotal_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LineTotal_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LineTotal_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid rowguid
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.rowguid);
            }
            set
            {
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.rowguid, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void rowguid_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Product Product
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.Product);
            }
            set
            {
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.Product, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.SalesOrderHeader SalesOrderHeader
        {
            get
            {
                return global::LightSwitchApplication.SalesOrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderHeader);
            }
            set
            {
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderHeader, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeader_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeader_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeader_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.SalesOrderDetail,
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass,
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.IImplementation,
                global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass>.Entry
                __SalesOrderDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.SalesOrderDetail.DetailsClass.__SalesOrderDetail_CreateNew,
                    global::LightSwitchApplication.SalesOrderDetail.DetailsClass.__SalesOrderDetail_Created,
                    global::LightSwitchApplication.SalesOrderDetail.DetailsClass.__SalesOrderDetail_AllowSaveWithErrors);
            private static global::LightSwitchApplication.SalesOrderDetail __SalesOrderDetail_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SalesOrderDetail> es)
            {
                return new global::LightSwitchApplication.SalesOrderDetail(es);
            }
            private static void __SalesOrderDetail_Created(global::LightSwitchApplication.SalesOrderDetail e)
            {
                e.SalesOrderDetail_Created();
            }
            private static bool __SalesOrderDetail_AllowSaveWithErrors(global::LightSwitchApplication.SalesOrderDetail e)
            {
                bool result = false;
                e.SalesOrderDetail_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int> SalesOrderID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int> SalesOrderDetailID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderDetailID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, short> OrderQty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.OrderQty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, short>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal> UnitPrice
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.UnitPrice) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal> UnitPriceDiscount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.UnitPriceDiscount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal> LineTotal
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.LineTotal) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.Guid> rowguid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.rowguid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.DateTime> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.Product> Product
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.Product) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.SalesOrderHeader> SalesOrderHeader
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderHeader) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int SalesOrderID { get; set; }
                new int SalesOrderDetailID { get; }
                new short OrderQty { get; set; }
                new decimal UnitPrice { get; set; }
                new decimal UnitPriceDiscount { get; set; }
                new decimal LineTotal { get; }
                new global::System.Guid rowguid { get; set; }
                new global::System.DateTime ModifiedDate { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Product { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation SalesOrderHeader { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>.Entry
                    SalesOrderID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>.Entry(
                        "SalesOrderID",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderID_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderID_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderID_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderID_GetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderID_SetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderID_OnValueChanged);
                private static void _SalesOrderID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderID, sf);
                }
                private static bool _SalesOrderID_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.SalesOrderID_IsReadOnly(ref result);
                    return result;
                }
                private static void _SalesOrderID_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SalesOrderID_Validate(r);
                }
                private static int _SalesOrderID_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.SalesOrderID;
                }
                private static void _SalesOrderID_SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, int v)
                {
                    d.ImplementationEntity.SalesOrderID = v;
                }
                private static void _SalesOrderID_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.SalesOrderID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>.Entry
                    SalesOrderDetailID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>.Entry(
                        "SalesOrderDetailID",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderDetailID_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderDetailID_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderDetailID_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderDetailID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderDetailID_OnValueChanged);
                private static void _SalesOrderDetailID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderDetailID, sf);
                }
                private static bool _SalesOrderDetailID_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.SalesOrderDetailID_IsReadOnly(ref result);
                    return result;
                }
                private static void _SalesOrderDetailID_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SalesOrderDetailID_Validate(r);
                }
                private static int _SalesOrderDetailID_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.SalesOrderDetailID;
                }
                private static void _SalesOrderDetailID_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.SalesOrderDetailID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, short>.Entry
                    OrderQty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, short>.Entry(
                        "OrderQty",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._OrderQty_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._OrderQty_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._OrderQty_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._OrderQty_GetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._OrderQty_SetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._OrderQty_OnValueChanged);
                private static void _OrderQty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, short>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._OrderQty, sf);
                }
                private static bool _OrderQty_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.OrderQty_IsReadOnly(ref result);
                    return result;
                }
                private static void _OrderQty_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OrderQty_Validate(r);
                }
                private static short _OrderQty_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.OrderQty;
                }
                private static void _OrderQty_SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, short v)
                {
                    d.ImplementationEntity.OrderQty = v;
                }
                private static void _OrderQty_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.OrderQty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Entry
                    UnitPrice = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Entry(
                        "UnitPrice",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPrice_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPrice_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPrice_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPrice_GetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPrice_SetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPrice_OnValueChanged);
                private static void _UnitPrice_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._UnitPrice, sf);
                }
                private static bool _UnitPrice_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.UnitPrice_IsReadOnly(ref result);
                    return result;
                }
                private static void _UnitPrice_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UnitPrice_Validate(r);
                }
                private static decimal _UnitPrice_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.UnitPrice;
                }
                private static void _UnitPrice_SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.UnitPrice = v;
                }
                private static void _UnitPrice_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.UnitPrice_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Entry
                    UnitPriceDiscount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Entry(
                        "UnitPriceDiscount",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPriceDiscount_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPriceDiscount_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPriceDiscount_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPriceDiscount_GetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPriceDiscount_SetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._UnitPriceDiscount_OnValueChanged);
                private static void _UnitPriceDiscount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._UnitPriceDiscount, sf);
                }
                private static bool _UnitPriceDiscount_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.UnitPriceDiscount_IsReadOnly(ref result);
                    return result;
                }
                private static void _UnitPriceDiscount_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UnitPriceDiscount_Validate(r);
                }
                private static decimal _UnitPriceDiscount_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.UnitPriceDiscount;
                }
                private static void _UnitPriceDiscount_SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.UnitPriceDiscount = v;
                }
                private static void _UnitPriceDiscount_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.UnitPriceDiscount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Entry
                    LineTotal = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Entry(
                        "LineTotal",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._LineTotal_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._LineTotal_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._LineTotal_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._LineTotal_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._LineTotal_OnValueChanged);
                private static void _LineTotal_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._LineTotal, sf);
                }
                private static bool _LineTotal_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.LineTotal_IsReadOnly(ref result);
                    return result;
                }
                private static void _LineTotal_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LineTotal_Validate(r);
                }
                private static decimal _LineTotal_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.LineTotal;
                }
                private static void _LineTotal_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.LineTotal_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.Guid>.Entry
                    rowguid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.Guid>.Entry(
                        "rowguid",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._rowguid_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._rowguid_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._rowguid_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._rowguid_GetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._rowguid_SetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._rowguid_OnValueChanged);
                private static void _rowguid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._rowguid, sf);
                }
                private static bool _rowguid_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.rowguid_IsReadOnly(ref result);
                    return result;
                }
                private static void _rowguid_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.rowguid_Validate(r);
                }
                private static global::System.Guid _rowguid_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.rowguid;
                }
                private static void _rowguid_SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.rowguid = v;
                }
                private static void _rowguid_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.rowguid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.DateTime>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.DateTime>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.DateTime _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.SalesOrderDetail.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Product = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Product",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._Product_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._Product_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._Product_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._Product_GetCoreImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._Product_GetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._Product_SetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._Product_Refresh,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._Product_OnValueChanged);
                private static void _Product_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Product, sf);
                }
                private static bool _Product_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.Product_IsReadOnly(ref result);
                    return result;
                }
                private static void _Product_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Product_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Product_GetCoreImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.Product;
                }
                private static global::LightSwitchApplication.Product _Product_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.Product, ref d._Product);
                }
                private static void _Product_SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, global::LightSwitchApplication.Product v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.Product, ref d._Product, (i, ev) => i.Product = ev, v);
                }
                private static void _Product_Refresh(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.Product, ref d._Product);
                }
                private static void _Product_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.Product_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Entry
                    SalesOrderHeader = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Entry(
                        "SalesOrderHeader",
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderHeader_Stub,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderHeader_ComputeIsReadOnly,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderHeader_Validate,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderHeader_GetCoreImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderHeader_GetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderHeader_SetImplementationValue,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderHeader_Refresh,
                        global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties._SalesOrderHeader_OnValueChanged);
                private static void _SalesOrderHeader_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Data> c, global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderHeader, sf);
                }
                private static bool _SalesOrderHeader_ComputeIsReadOnly(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    bool result = false;
                    e.SalesOrderHeader_IsReadOnly(ref result);
                    return result;
                }
                private static void _SalesOrderHeader_Validate(global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SalesOrderHeader_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _SalesOrderHeader_GetCoreImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.SalesOrderHeader;
                }
                private static global::LightSwitchApplication.SalesOrderHeader _SalesOrderHeader_GetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.SalesOrderHeader, global::LightSwitchApplication.SalesOrderHeader.DetailsClass>(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderHeader, ref d._SalesOrderHeader);
                }
                private static void _SalesOrderHeader_SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d, global::LightSwitchApplication.SalesOrderHeader v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderHeader, ref d._SalesOrderHeader, (i, ev) => i.SalesOrderHeader = ev, v);
                }
                private static void _SalesOrderHeader_Refresh(global::LightSwitchApplication.SalesOrderDetail.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.SalesOrderDetail.DetailsClass.PropertySetProperties.SalesOrderHeader, ref d._SalesOrderHeader);
                }
                private static void _SalesOrderHeader_OnValueChanged(global::LightSwitchApplication.SalesOrderDetail e)
                {
                    e.SalesOrderHeader_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>.Data _SalesOrderID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, int>.Data _SalesOrderDetailID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, short>.Data _OrderQty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Data _UnitPrice;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Data _UnitPriceDiscount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, decimal>.Data _LineTotal;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.Guid>.Data _rowguid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::System.DateTime>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.Product>.Data _Product;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SalesOrderDetail, global::LightSwitchApplication.SalesOrderDetail.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Data _SalesOrderHeader;
            
        }
    
        #endregion
    }
    
    #endregion
}
