

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class BuildVersion : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the BuildVersion entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public BuildVersion()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public BuildVersion(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BuildVersion> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.BuildVersion.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BuildVersion_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BuildVersion_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte SystemInformationID
        {
            get
            {
                return global::LightSwitchApplication.BuildVersion.DetailsClass.GetValue(this, global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.SystemInformationID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SystemInformationID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SystemInformationID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SystemInformationID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Database_Version
        {
            get
            {
                return global::LightSwitchApplication.BuildVersion.DetailsClass.GetValue(this, global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.Database_Version);
            }
            set
            {
                global::LightSwitchApplication.BuildVersion.DetailsClass.SetValue(this, global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.Database_Version, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Database_Version_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Database_Version_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Database_Version_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime VersionDate
        {
            get
            {
                return global::LightSwitchApplication.BuildVersion.DetailsClass.GetValue(this, global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.VersionDate);
            }
            set
            {
                global::LightSwitchApplication.BuildVersion.DetailsClass.SetValue(this, global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.VersionDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.BuildVersion.DetailsClass.GetValue(this, global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.BuildVersion.DetailsClass.SetValue(this, global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.BuildVersion,
                global::LightSwitchApplication.BuildVersion.DetailsClass,
                global::LightSwitchApplication.BuildVersion.DetailsClass.IImplementation,
                global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.SystemInformationID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass>.Entry
                __BuildVersionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass>.Entry(
                    global::LightSwitchApplication.BuildVersion.DetailsClass.__BuildVersion_CreateNew,
                    global::LightSwitchApplication.BuildVersion.DetailsClass.__BuildVersion_Created,
                    global::LightSwitchApplication.BuildVersion.DetailsClass.__BuildVersion_AllowSaveWithErrors);
            private static global::LightSwitchApplication.BuildVersion __BuildVersion_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BuildVersion> es)
            {
                return new global::LightSwitchApplication.BuildVersion(es);
            }
            private static void __BuildVersion_Created(global::LightSwitchApplication.BuildVersion e)
            {
                e.BuildVersion_Created();
            }
            private static bool __BuildVersion_AllowSaveWithErrors(global::LightSwitchApplication.BuildVersion e)
            {
                bool result = false;
                e.BuildVersion_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, byte> SystemInformationID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.SystemInformationID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, byte>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, string> Database_Version
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.Database_Version) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime> VersionDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.VersionDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new byte SystemInformationID { get; }
                new string Database_Version { get; set; }
                new global::System.DateTime VersionDate { get; set; }
                new global::System.DateTime ModifiedDate { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, byte>.Entry
                    SystemInformationID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, byte>.Entry(
                        "SystemInformationID",
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._SystemInformationID_Stub,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._SystemInformationID_ComputeIsReadOnly,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._SystemInformationID_Validate,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._SystemInformationID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._SystemInformationID_OnValueChanged);
                private static void _SystemInformationID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BuildVersion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, byte>.Data> c, global::LightSwitchApplication.BuildVersion.DetailsClass d, object sf)
                {
                    c(d, ref d._SystemInformationID, sf);
                }
                private static bool _SystemInformationID_ComputeIsReadOnly(global::LightSwitchApplication.BuildVersion e)
                {
                    bool result = false;
                    e.SystemInformationID_IsReadOnly(ref result);
                    return result;
                }
                private static void _SystemInformationID_Validate(global::LightSwitchApplication.BuildVersion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SystemInformationID_Validate(r);
                }
                private static byte _SystemInformationID_GetImplementationValue(global::LightSwitchApplication.BuildVersion.DetailsClass d)
                {
                    return d.ImplementationEntity.SystemInformationID;
                }
                private static void _SystemInformationID_OnValueChanged(global::LightSwitchApplication.BuildVersion e)
                {
                    e.SystemInformationID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, string>.Entry
                    Database_Version = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, string>.Entry(
                        "Database_Version",
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._Database_Version_Stub,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._Database_Version_ComputeIsReadOnly,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._Database_Version_Validate,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._Database_Version_GetImplementationValue,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._Database_Version_SetImplementationValue,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._Database_Version_OnValueChanged);
                private static void _Database_Version_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BuildVersion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, string>.Data> c, global::LightSwitchApplication.BuildVersion.DetailsClass d, object sf)
                {
                    c(d, ref d._Database_Version, sf);
                }
                private static bool _Database_Version_ComputeIsReadOnly(global::LightSwitchApplication.BuildVersion e)
                {
                    bool result = false;
                    e.Database_Version_IsReadOnly(ref result);
                    return result;
                }
                private static void _Database_Version_Validate(global::LightSwitchApplication.BuildVersion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Database_Version_Validate(r);
                }
                private static string _Database_Version_GetImplementationValue(global::LightSwitchApplication.BuildVersion.DetailsClass d)
                {
                    return d.ImplementationEntity.Database_Version;
                }
                private static void _Database_Version_SetImplementationValue(global::LightSwitchApplication.BuildVersion.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Database_Version = v;
                }
                private static void _Database_Version_OnValueChanged(global::LightSwitchApplication.BuildVersion e)
                {
                    e.Database_Version_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>.Entry
                    VersionDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>.Entry(
                        "VersionDate",
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._VersionDate_Stub,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._VersionDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._VersionDate_Validate,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._VersionDate_GetImplementationValue,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._VersionDate_SetImplementationValue,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._VersionDate_OnValueChanged);
                private static void _VersionDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BuildVersion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.BuildVersion.DetailsClass d, object sf)
                {
                    c(d, ref d._VersionDate, sf);
                }
                private static bool _VersionDate_ComputeIsReadOnly(global::LightSwitchApplication.BuildVersion e)
                {
                    bool result = false;
                    e.VersionDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _VersionDate_Validate(global::LightSwitchApplication.BuildVersion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VersionDate_Validate(r);
                }
                private static global::System.DateTime _VersionDate_GetImplementationValue(global::LightSwitchApplication.BuildVersion.DetailsClass d)
                {
                    return d.ImplementationEntity.VersionDate;
                }
                private static void _VersionDate_SetImplementationValue(global::LightSwitchApplication.BuildVersion.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.VersionDate = global::LightSwitchApplication.BuildVersion.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _VersionDate_OnValueChanged(global::LightSwitchApplication.BuildVersion e)
                {
                    e.VersionDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.BuildVersion.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BuildVersion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.BuildVersion.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.BuildVersion e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.BuildVersion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.DateTime _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.BuildVersion.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.BuildVersion.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.BuildVersion.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.BuildVersion e)
                {
                    e.ModifiedDate_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, byte>.Data _SystemInformationID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, string>.Data _Database_Version;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>.Data _VersionDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BuildVersion, global::LightSwitchApplication.BuildVersion.DetailsClass, global::System.DateTime>.Data _ModifiedDate;
            
        }
    
        #endregion
    }
    
    #endregion
}
